"""'changed'

Revision ID: 0de3cd6232cc
Revises: 770d0d1b21a1
Create Date: 2022-06-07 15:32:21.097865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de3cd6232cc'
down_revision = '770d0d1b21a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
