"""empty message

Revision ID: 487b0469c767
Revises: 70b0346364ab
Create Date: 2022-06-07 15:40:14.049486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487b0469c767'
down_revision = '70b0346364ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
