"""empty message

Revision ID: b2795e296520
Revises: 3a53b902b0ff
Create Date: 2022-06-07 15:45:15.764062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2795e296520'
down_revision = '3a53b902b0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
